version: '3'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: r00t
